In [1]:
import numpy as np


In [2]:
zeros = np.zeros((3,2,3,))


In [3]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
ones = np.ones((3,2,3))

In [5]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
inserted_array = np.insert(zeros,1,ones,axis=0)

In [7]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [8]:
new_insert = np.insert(zeros,1,ones,axis=1)

ValueError: could not broadcast input array from shape (2,3,3) into shape (3,3,3)

In [9]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
new_insert = np.insert(zeros,1,ones,axis=1)

ValueError: could not broadcast input array from shape (2,3,3) into shape (3,3,3)

In [12]:
new = np.array(3,2)


TypeError: Cannot interpret '2' as a data type

In [13]:
new =np.random.random(3,2)


TypeError: random() takes at most 1 positional argument (2 given)

In [14]:
new = np.random.ran(3,2)

AttributeError: module 'numpy.random' has no attribute 'ran'

In [15]:
new = np.random.rand(3,2)


In [16]:
new

array([[0.88955666, 0.12015057],
       [0.49484869, 0.4496471 ],
       [0.98235447, 0.61595366]])

In [17]:
old = np.random.rand(3,2)

In [18]:
old

array([[0.20776958, 0.25361381],
       [0.19759008, 0.12835553],
       [0.58632784, 0.03135906]])

In [19]:
new_insert = np.insert(new,1,old,axis=1)

ValueError: could not broadcast input array from shape (2,3) into shape (3,3)

In [20]:
np.old


AttributeError: module 'numpy' has no attribute 'old'

In [21]:
old

array([[0.20776958, 0.25361381],
       [0.19759008, 0.12835553],
       [0.58632784, 0.03135906]])

In [22]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
zeros[0]


array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.delete(zeros,0)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [26]:
np.delete(zeros,0,axis=1)

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [27]:
np.delete(zeros,0,axis=2
         )

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])